---
namespace: ircproxy
commonLabels:
  app: ircproxy

resources:
  - deployment.yml

configMapGenerator:
  - name: init-scripts
    files:
      - init-znc.sh
      - init-bitlbee.sh

  - name: bitlbee-config
    files:
      - bitlbee.conf

generators:
  - ./secret-generator.yml
