---
namespace: ircproxy
commonLabels:
  app: ircproxy

bases:
  - ../base

configMapGenerator:
  - name: init-scripts
    files:
      - init-znc.sh
      - init-bitlbee.sh

generators:
  - ./secret-generator.yml

patches:
  - path: patch_deployment.yml
    target:
      kind: Deployment
      name: ircproxy
