apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircproxy
spec:
  template:
    spec:
      volumes:
        # ssh keys used for read-only access to private
        # github repositories.
        - name: deploykeys
          secret:
            secretName: deploykeys
            defaultMode: 0400

        # makes script from the init-scripts configmap available on
        # the filesystem. these scripts are responsible for grabbing
        # the initial bitlbee and znc configuration from our private
        # github repositories.
        - name: init-scripts
          configMap:
            name: init-scripts

        # exposes the bitblee-config secret as /etc/bitlbee. currently
        # just sets bitlbee's operpassword.
        - name: bitlbee-config
          secret:
            secretName: bitlbee-config

        # expose the znc ssl certificate from the znc-certificate secret
        # on the filesystem. The znc init script will copy this into
        # the correct location when the pod starts up.
        - name: znc-certificate
          secret:
            secretName: znc-certificate

      initContainers:
        # the init-znc container will populate the znc-state volume
        # with initial configuration (from a private github repository)
        # if it is empty. on every startup it copies the znc ssl 
        # certificate from the znc-certificate secret into the proper
        # location.
        - name: init-znc
          image: alpine/git:v2.26.2
          command: ['sh']
          args: ['/tmp/init/init-znc.sh']
          volumeMounts:
            - mountPath: /znc-data
              name: znc-state
            - mountPath: /znc-data/moddata/log
              name: znc-logs
            - mountPath: /data/znc-certificate
              name: znc-certificate
              readOnly: true
            - mountPath: /tmp/init
              name: init-scripts
              readOnly: true
            - mountPath: /tmp/deploykeys
              name: deploykeys


        # the init-bitlbee container will populate the bitlbee-state volume
        # with initial configuration (from a private github repository)
        # if it is empty.
        - name: init-bitlbee
          image: alpine/git:v2.26.2
          command: ['sh']
          args: ['/tmp/init/init-bitlbee.sh']
          volumeMounts:
            - mountPath: /bitlbee-data
              name: bitlbee-state
            - mountPath: /tmp/init
              name: init-scripts
              readOnly: true
            - mountPath: /tmp/deploykeys
              name: deploykeys
      containers:

        # patches the bitlbee container to mount the bitlbee-config
        # secret on /etc/bitlbee.
        - name: bitlbee
          volumeMounts:
            - mountPath: /etc/bitlbee
              name: bitlbee-config
