---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ircproxy
spec:
  template:
    spec:
      volumes:
        - name: deploykeys
          secret:
            secretName: deploykeys
            defaultMode: 0400
        - name: init-scripts
          configMap:
            name: init-scripts
        - name: bitlbee-config
          secret:
            secretName: bitlbee-config
        - name: znc-certificate
          secret:
            secretName: znc-certificate
      initContainers:
        - name: init-znc
          image: alpine/git:v2.26.2
          command: ['sh']
          args: ['/tmp/init/init-znc.sh']
          volumeMounts:
            - mountPath: /znc-data
              name: znc-state
            - mountPath: /znc-data/moddata/log
              name: znc-logs
            - mountPath: /data/znc-certificate
              name: znc-certificate
              readOnly: true
            - mountPath: /tmp/init
              name: init-scripts
              readOnly: true
            - mountPath: /tmp/deploykeys
              name: deploykeys
        - name: init-bitlbee
          image: alpine/git:v2.26.2
          command: ['sh']
          args: ['/tmp/init/init-bitlbee.sh']
          volumeMounts:
            - mountPath: /var/lib/bitlbee
              name: bitlbee-state
            - mountPath: /tmp/init
              name: init-scripts
              readOnly: true
            - mountPath: /tmp/deploykeys
              name: deploykeys
      containers:
        - name: bitlbee
          volumeMounts:
            - mountPath: /etc/bitlbee
              name: bitlbee-config
