apiVersion: v1
kind: Service
metadata:
  name: irc-ssl
spec:
  selector:
    app: ircproxy
  ports:
    - protocol: TCP
      port: 6697
      targetPort: irc-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: web-ssl
spec:
  selector:
    app: ircproxy
  ports:
    - protocol: TCP
      port: 8443
      targetPort: web-ssl
